"""Establish relationship bln mentee and task tables.

Revision ID: 1389ac39d488
Revises: 979fa9626280
Create Date: 2024-01-12 15:39:28.956636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1389ac39d488'
down_revision = '979fa9626280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mentees_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'mentees', ['mentees_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('mentees_id')

    # ### end Alembic commands ###
